import { meta, shopify, starbucks, tesla } from "../assets/images";
import {
    car,
    contact,
    css,
    estate,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    motion,
    mui,
    nextjs,
    nodejs,
    pricewise,
    react,
    redux,
    sass,
    snapgram,
    summiz,
    tailwindcss,
    threads,
    typescript,
    tripadvisor,
    shirt,
    food,
    selenium,
    cognizant,
    inmovidu,
    medplus,
    docker,
    angular,
    framer,
    threejs,
    bootstrap,
    python,
    django,
    sql,
    instagram,
    aws,
} from "../assets/icons";

export const skills = [
    {
        imageUrl: python,
        name: "Python",
        type: "Backend",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    },
    {
        imageUrl: docker,
        name: "Docker",
        type: "DevOps",
    },
    {
        imageUrl: aws,
        name: "AWS",
        type: "DevOps",
    },
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: sass,
        name: "Sass",
        type: "Frontend",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
    {
        imageUrl: django,
        name: "Django",
        type: "Backend",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: sql,
        name: "SQL",
        type: "Database",
    },
    {
        imageUrl: motion,
        name: "Motion",
        type: "Animation",
    },
    {
        imageUrl: mui,
        name: "Material-UI",
        type: "Frontend",
    },
    {
        imageUrl: bootstrap,
        name: "Bootstrap",
        type: "Frontend",
    },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: angular,
        name: "Angular",
        type: "Frontend",
    },
    {
        imageUrl: redux,
        name: "Redux",
        type: "State Management",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: threejs,
        name: "Three.js",
        type: "Frontend",
    },
    {
        imageUrl: framer,
        name: "Framer-Motion",
        type: "Frontend",
    },
    {
        imageUrl: selenium,
        name: "Selenium",
        type: "Testing",
    },
];

export const experiences = [
    {
        title: "Python Developer",
        company_name: "Inmovidu Tech",
        icon: inmovidu,
        iconBg: "#f7d679",
        date: "Aug 2021 - Feb 22",
        points: [
            "Collaborating with senior developers and teams to understand project requirements and contribute to the development process.",
            "Assisting in the design and implementation of software features and functionalities.",
            "Participating in code reviews and debugging sessions to identify and fix software bugs.",
        ],
    },
    {
        title: "Quality Assurance and Testing Engineer",
        company_name: "Cognizant Technology",
        icon: cognizant,
        iconBg: "#accbe1",
        date: "March 2022 - June 22",
        points: [
            "Designing and implementing automated test suites using Java and Selenium WebDriver, ensuring efficient test coverage and reliability.",
            "Developing robust and scalable test scripts and frameworks to perform functional, regression, and performance testing.",
            "Collaborating closely with development teams to identify and rectify software defects, ensuring the delivery of high-quality software.",
            "Creating detailed test plans, test cases, and test reports to effectively communicate testing outcomes and ensure traceability.",
            // "Contributing to continuous integration and continuous deployment (CI/CD) pipelines to automate testing processes and shorten feedback loops.",
            // "Identifying areas for process improvement and implementing best practices to enhance the overall software testing strategy.",
        ],
    },
    {
        title: "Web Developer",
        company_name: "Medplus Health Solutions",
        icon: medplus,
        iconBg: "#fbc3bc",
        date: "Aug 2022 - Present",
        points: [
            "Designing and implementing backend functionalities using Django & Express to ensure the scalability, security, and performance of web applications.",
            "Creating dynamic and interactive user interfaces with Angular and React, incorporating modern design principles and best practices.",
            "Writing clean, modular, and well-documented code following industry standards and coding conventions.",
            "Implementing responsive and mobile-friendly designs to enhance user experience across various devices and screen sizes.",
        ],
    },
    // {
    //     title: "React Native Developer",
    //     company_name: "Tesla",
    //     icon: tesla,
    //     iconBg: "#fbc3bc",
    //     date: "Jan 2021 - Feb 2022",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
    // {
    //     title: "Web Developer",
    //     company_name: "Shopify",
    //     icon: shopify,
    //     iconBg: "#b7e4c7",
    //     date: "Jan 2022 - Jan 2023",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
    // {
    //     title: "Full stack Developer",
    //     company_name: "Meta",
    //     icon: meta,
    //     iconBg: "#a2d2ff",
    //     date: "Jan 2023 - Present",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
];

export const socialLinks = [
    {
        name: 'Instagram',
        iconUrl: instagram,
        link: 'https://www.instagram.com/just_cal_ab?igsh=MXNwcDl2Ym5uNzZvdg%3D%3D&utm_source=qr',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/deadlock-mv',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/abmath374',
    }
];

export const projects = [
    {
        iconUrl: shirt,
        theme: 'btn-back-blue',
        name: '3D Shirt Desginer Studio',
        description: 'Developed a web application that offers users the ability to personalize shirts by adding logos, textures, and choosing from various color schemes.',
        link: 'https://amvstudio.netlify.app/',
        github: 'https://github.com/deadlock-mv/3d-Shirt-Designer',
    },
    {
        iconUrl: tripadvisor,
        theme: 'btn-back-green',
        name: 'Trip-Advisor',
        description: 'Designed and implemented a web application that serves as a comprehensive guide for travelers, offering insights into various tourist attractions, restaurants, and hotels based on their location.',
        link: 'https://mvtrip-advisor.netlify.app/',
        github: 'https://github.com/deadlock-mv/trip-advisor',
    },
    {
        iconUrl: food,
        theme: 'btn-back-red',
        name: 'Food Delivery Application',
        description: 'Designed and implemented a comprehensive web application for managing food delivery operations like order processing, track delivery status in real-time and manage inventory.',
        github: 'https://github.com/deadlock-mv/Food-Delivery',
    },
    {
        iconUrl: pricewise,
        theme: 'btn-back-pink',
        name: 'E-Commerce API',
        description: 'Developed a robust backend API for powering an e-commerce platform of product management, order processing, user authentication, and inventory management.',
        github: 'https://github.com/deadlock-mv/E-Commerce-API',
    },
];